# Generated by Django 4.1.5 on 2023-01-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('latitude', models.CharField(max_length=50)),
                ('hardness', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('img_url', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
