# Generated by Django 4.1.5 on 2023-01-10 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_hardness_mountain_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountain',
            name='img_url',
        ),
        migrations.CreateModel(
            name='Mountain_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mountain')),
            ],
        ),
    ]
