# Generated by Django 4.1.5 on 2023-01-13 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_mountain_img_url_mountain_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountain',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='mountain',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='mountain_img',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='mountain_img',
            name='modify_date',
        ),
    ]
