# Generated by Django 4.1.5 on 2023-01-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_author_reply_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
